name: miniapp_package
description: "Taxi"
homepage:
version: 0.0.13

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^12.0.1

#  balady_host_sdk:
#    git:
#      url: https://github.com/AmmarAbdalqader/balady_host_sdk

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
